### ISSUE TITLE
No link to this repo from https://www.npmjs.org/package/commandliner

### ISSUE THREAD

**Issue by magnusstubman** [finnp/commandLiner#1]
I had to feakin' google it! :-1:

See here for example on how to add the repo to the module: https://github.com/remy/nodemon/blob/master/package.json#L11

**Comment by finnp** [comment]
Thanks, but if you would have made a small peak into the package.json here, you would have noticed the typos there and could have sent a quick pull request with [the change](https://github.com/finnp/commandLiner/commit/a7f3162b44961281ad35e9db1e52eb71efa18353).

However thanks for letting me know, I also hate when this is missing. It's updated in the newest version on npm.
