### ISSUE TITLE
Cannot generate docker commands

### ISSUE THREAD

**Issue by magnusstubman** [finnp/commandLiner#3]
I'm trying to use CommandLiner to generate commands for Docker.

```
$ docker build -t randomNamehere .
<some output>
$ docker run randomSha256Here
<some output>
```

So there is actually at least two issues here:
1. argument may not be just a dot (.) but will become quote-dot-quote ("."), which is not the same thing
2. "arguments" such as build/run in the example above is not allowed before options (-t)

I know that there are many other CLI applications which also has similare option formats.

**Comment by finnp** [comment]
Yeah totally. I have to think of what would be a good API. Maybe a option like `quoted`, which set to false would not wrap the last String in quotes? That doesnt feel very neat though.

The other issue could be solved with a `command` attribute. 

Your example then would something like this

```
var docker = new Commandliner('docker', {t: 'randomNamehere'}, 'Hello, there!');
docker.quoted = false;
docker.command= 'build';
```

And maybe a short Object creator like:

```
var docker = new Commandliner('docker', 'build', {t: 'randomNamehere'}, 'Hello, there!', false);
```

**Comment by magnusstubman** [comment]
I'd say that the best thing would be an ordered array with something like

```
var arr1 = ['docker', 'build', {t: 'something'}, 'Hello, there!'];
var docker1 = new Commandliner(arr1);
var arr2 = ['docker', 'run', 'randomName', '.'];
var docker2 = new Commandliner(arr2);
```

And only add double quotes if there are none and the string contains a space. This way, users who need quotes around one-word strings, can provide them themselves. So in the example above, 'Hello, there!' would become "Hello, there!" on the command line.

**Comment by finnp** [comment]
Sounds good. However I want the commandliner to be an object which basically turns the command into a little nice wraper. So what you describe might actually better be part of the `build` command. However I am still not sure about the quotes. Becaues quotes only on spaces is not enough, because they should also prevent people from using `&` for launching a new command. So I will look a bit into shell escaping first. Also I read that `spawn` is actually preferable for this kind of use cases. So I will also look into that.

**Comment by finnp** [comment]
So now it should work with the new version `0.2.0` I just published on npm.

Your examples work like this with the `build` function (where you get the string directly):

``` javascript
var arr1 = ['docker', 'build', {t: 'something'}, 'Hello, there!'];
var docker1 = Commandliner.build(arr1);
var arr2 = ;
var docker2 = Commandliner.build(arr2);
```

Alternatively you can use Commandliner with:

``` javascript
var docker1 = new Commandliner('docker', 'build', {t: 'something'}, 'Hello, there!']);
var docker2 = new Commandliner('docker', 'run', {}, ['randomName', '.']); 
// or
var docker2 = new Commandliner('docker', 'run');
docker2.args =  ['randomName', '.'];
```
